- WebContent/css/src/salon.css
- WebContent/salon.html
issue：#2
サロン情報管理ページのHTML部分およびCSSを作成した。
> サロン情報管理ページのティザー

- WebContent/css/src/stylist.css
- WebContent/salon.html
- WebContent/stylist.html
issue：#2
スタッフ情報管理ページのHTML部分およびCSSを作成した。
> スタッフ情報管理ページのティザー

- WebContent/css/src/service.css
- WebContent/service.html
issue：#2
サービス情報管理ページのHTML部分およびCSSを作成した。
> サービス情報管理ページのティザー

- WebContent/coupon.html
- WebContent/css/src/coupon.css
- WebContent/service.html
- WebContent/stylist.html
issue：#2
クーポン情報管理ページのHTML部分およびCSSを作成した。
> クーポン情報管理ページのティザー

- WebContent/album.html
- WebContent/css/src/album.css
issue：#2
アルバム情報管理ページのHTML部分およびCSSを作成した。
> アルバム管理ページのティザー

- WebContent/css/src/map.css
- WebContent/map.html
issue：#2
地図情報管理ページのHTML部分およびCSSを作成した。
> 地図情報管理ページのティザー

- .gitignore
- Gruntfile.js
- WebContent/album.html
- WebContent/coupon.html
- WebContent/js/src/index.js
- WebContent/js/src/index/index.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
issue：#3
* ログインページにアクセスした際にセッションが作成されている場合は、サロン管理ページにリダイレクトするように。
* ログインページ以外にアクセスした際にセッションが作成されていない場合は、ログインページにリダイレクトするように。
> ログインページにリダイレクトする部分とログインページからリダイレクトする部分を作成

- .gitignore
- Gruntfile.js
- README.md
- WebContent/js/app.js
- WebContent/js/src/common.js
- WebContent/js/src/concat/index.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/salon.js
- WebContent/salon.html
issue：#4
* AjaxによりDBからデータを取得し、ReactによりDOMに値を代入するように
* HTMLをReactに対応するように
* 画面遷移時にリロードするように
> サロン情報管理ページにDBの内容を表示するように

- WebContent/album.html
- WebContent/coupon.html
- WebContent/js/src/common.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
issue：#4 
* 閲覧中のページのタブに色をつけるようにした
* リロードボタン押下時に画面リロードを行うようにした
> アクティブなページのタブに色をつけるように。リロードボタン押下時は画面リロードを行うように。

- WebContent/coupon.html
- WebContent/css/src/coupon.css
- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/coupon.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/service.js
issue：#4
* DBから取得した情報をクーポン情報管理画面に表示するように
* DBから取得した情報をクーポン一覧欄に表示するように
```json
{
"coupon":
[
{
"t_coupon_Id": "2",
"t_coupon_couponKindId": "2",
"t_coupon_name": "クーポン名2",
"t_coupon_detailText": "説明文2",
"t_coupon_price": "400",
"t_coupon_deadLine": "2015年6月末まで",
"t_coupon_presentationCondition": "提示条件2",
"t_coupon_useCondition": "利用条件２",
"t_coupon_imagePath": "img/avatar.png"
},
{
"t_coupon_Id": "1",
"t_coupon_couponKindId": "1",
"t_coupon_name": "クーポン名1",
"t_coupon_detailText": "説明文1",
"t_coupon_price": "100",
"t_coupon_deadLine": "2015年8月末まで",
"t_coupon_presentationCondition": "提示条件１",
"t_coupon_useCondition": "利用条件１",
"t_coupon_imagePath": ""
}
]
}
```
> クーポン情報管理画面にDBから取得した情報を表示するように

- WebContent/css/src/stylist.css
- WebContent/js/src/common.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/stylist.js
- WebContent/stylist.html
issue：#4
* DBから取得した情報をスタッフ情報管理画面に埋め込むように
* DBから取得したメニュー一覧をServiceMapingに埋め込むように
* DBから取得した情報をスタッフ一覧に埋め込むように
```
{
"stylist":[
{
"t_stylist_Id": "2",
"t_stylist_name": "スタイリスト2",
"t_stylist_sex": "1",
"t_stylist_phoneNumber": "000-1234-5678",
"t_stylist_mail": "sample@mail.com",
"t_stylist_imagePath": "img/avatar.png",
"t_stylist_birth": "1999-05-06 00:00:00",
"t_stylist_position": "チーフ",
"t_stylist_experienceYear": "2",
"t_stylist_specialMenu": "特技説明文２",
"t_stylist_message": "自己PR２",
"t_menu_t_menu_id": "1,2"
},
{
"t_stylist_Id": "1",
"t_stylist_name": "スタイリスト1",
"t_stylist_sex": "0",
"t_stylist_phoneNumber": "000-1234-9876",
"t_stylist_mail": "sample2@mail.com",
"t_stylist_imagePath": "",
"t_stylist_birth": "1999-08-08 00:00:00",
"t_stylist_position": "アシスタント", …
```
> スタッフ情報管理画面にDBから取得した情報を表示するように

- WebContent/css/src/salon.css
- WebContent/js/src/common.js
- WebContent/js/src/concat/index.js
- WebContent/js/src/index.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/salon.js
- WebContent/salon.html
issue：#6
サロン情報管理ページの登録ボタン押下時に、画面の上方をDBへ登録するように
> サロン情報管理ページの登録ボタン実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/service.js
issue：#6
登録ボタン押下時にサービス情報管理ページの情報をDBに投げるように
> サービス情報管理ページの登録ボタン実装

- WebContent/js/src/album.js
- WebContent/js/src/common.js
- WebContent/js/src/jsx/album.js
issue：#6
アルバム管理ページの情報をDBに投げるように
> アルバム管理ページ登録ボタン実装

- WebContent/coupon.html
- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/coupon.js
issue：#6
* クーポン情報を登録時にDBに投げるように
* クーポン種別欄を作成
> クーポン情報画面に登録ボタンを実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/map.js
- WebContent/js/src/map.js
issue：#6
地図情報管理ページの登録ボタン押下時にDBに情報を投げるように
> 地図情報管理画面に登録ボタン実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/stylist.js
issue：#6
スタッフ情報管理画面にて登録ボタン押下時にDBに情報を投げるように
> スタッフ情報管理画面にて登録ボタン実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/stylist.js
issue：#4 
* 編集ボタンを実装
* 削除ボタンを実装
* 登録時の日時形式を修正
> スタッフ情報管理画面にて編集ボタンと削除ボタンを実装

- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/coupon.js
issue：#4
* 編集ボタンを実装
* 削除ボタンを実装
* スタッフ情報削除のAPIパスを修正
> クーポン情報管理画面にて編集ボタンと削除ボタンを実装した

- WebContent/js/src/album.js
- WebContent/js/src/common.js
- WebContent/js/src/jsx/album.js
> アルバム管理ページにて編集ボタンと削除ボタンを実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/service.js
issue：#4
* 編集ボタンを実装
* 削除ボタンを実装
> サービス情報管理画面にて編集ボタンと削除ボタンを実装

- WebContent/js/src/common.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/stylist.js
issue：#4
* ServiceMapingの登録ボタンを実装
* ServiceMapingの削除ボタンを実装
> スタッフ情報管理画面のServiceMapingの登録ボタンと削除ボタンを実装

- WebContent/album.html
- WebContent/coupon.html
- WebContent/index.html
- WebContent/js/config.js
- WebContent/js/src/album.js
- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/album.js
- WebContent/js/src/jsx/coupon.js
- WebContent/js/src/jsx/map.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/map.js
- WebContent/js/src/salon.js
- WebContent/js/src/service.js
- WebContent/js/src/stylist.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
issue：#6 
* Set系APIにIDを投げるように
* APIルートを外出しするように(config.js)
> Set系APIにIDを投げるように

- WebContent/js/config.js
- WebContent/js/src/common.js
- WebContent/js/src/concat/index.js
- WebContent/js/src/index.js
issue：#6
* 叩くAPI名からActionを削除し先頭を小文字にした
> API名が間違っていたため修正

- WebContent/album.html
- WebContent/coupon.html
- WebContent/js/src/album.js
- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/album.js
- WebContent/js/src/jsx/coupon.js
- WebContent/js/src/jsx/map.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/map.js
- WebContent/js/src/salon.js
- WebContent/js/src/service.js
- WebContent/js/src/stylist.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
> 画像アップロード実装

- WebContent/js/src/album.js
- WebContent/js/src/coupon.js
- WebContent/js/src/jsx/album.js
- WebContent/js/src/jsx/coupon.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/service.js
- WebContent/js/src/stylist.js
issue：#4
以下のページにアクセスした際に登録情報を空にし、新規登録できるようにした。
* アルバム管理ページ
* クーポン管理ページ
* サービス管理ページ
* スタッフ管理ページ
> アクセス時に新規登録できるように

- WebContent/album.html
- WebContent/coupon.html
- WebContent/js/src/album.js
- WebContent/js/src/common.js
- WebContent/js/src/coupon.js
- WebContent/js/src/index.js
- WebContent/js/src/jsx/album.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/salon.js
- WebContent/js/src/service.js
- WebContent/js/src/stylist.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
* サニタイズのバグ修正
* Ajaxでサーバからデータを受け取った際にjsonではなくtextで受け取ってjsonにparseするように
* ログアウト機能が実行できるように修正
> develop to master(Ajaxで取得するデータ型の修正)

- WebContent/album.html
- WebContent/coupon.html
- WebContent/css/src/stylist.css
- WebContent/index.html
- WebContent/js/src/album.js
- WebContent/js/src/coupon.js
- WebContent/js/src/index.js
- WebContent/js/src/jsx/album.js
- WebContent/js/src/jsx/coupon.js
- WebContent/js/src/jsx/salon.js
- WebContent/js/src/jsx/service.js
- WebContent/js/src/jsx/stylist.js
- WebContent/js/src/salon.js
- WebContent/js/src/service.js
- WebContent/js/src/stylist.js
- WebContent/map.html
- WebContent/salon.html
- WebContent/service.html
- WebContent/stylist.html
なお、ファイルを選択の部分はHTML5の機能なので、表示されるテキストはブラウザ依存となるため、中国語に自動変換される。
> develop to master(中国語対応)
